const eris = require('eris');
const bot = new eris.Client('Mzg0NDY4NjgyNzg2NzM0MDgw.Whs-XQ.z1uW0QKIPCTw8Py2FBWP1yRoZJE');
bot.on('ready', () => {
   console.log('Connected and ready.');
});
bot.on('messageCreate', async (msg) => {
   const botWasMentioned = msg.mentions.find(
       mentionedUser => mentionedUser.id === bot.user.id,
   );

   if (botWasMentioned) {
       try {
           await msg.channel.createMessage('Present');
       } catch (err) {
           console.warn('Failed to respond to mention.');
           console.warn(err);
       }
   }
});

bot.on('error', err => {
   console.warn(err);
});

bot.connect();
